# -*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Import('env')

gexml = env.sharedLib('gexml', ['khxml.cpp'],
                      LIBS=['geutil', 'xerces-c', env['png_ver']])

env.install('common_lib', [gexml])


test_idlfiles = ['test_classes',
                 ]

env.idl(map(lambda n: n+'.idl', test_idlfiles))

env.test('idl_tests',
         ['idl_tests.cc',
          map(lambda n: '.idl/'+n+'.cpp', test_idlfiles),
          ],
         LIBS=['gexml', 'gecommon', 'geutil',
               'QtGui', 'QtCore', 'xerces-c', 'gtest'])

env.test('khxml_unittest',
         'khxml_unittest.cpp',
         LIBS=['geutil', 'xerces-c', env['png_ver'], 'QtGui', 'QtCore',
               'gexml', 'gecommon', 'gtest'])
