#-*- Python -*-
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')
import os
env = env.Clone()
env.UpdateCppflagsForSkia()

sources = [ 'crawlersource.cpp',
            'archivesource.cpp',
            'archivewriter.cpp',
            'httpcrawlersource.cpp',
            'crawlcompare.cpp',
            'kmllog.cpp',
            'comparevector.cpp',
            'compareterrain.cpp',
            ]

gecrawllib = env.sharedLib('gecrawllib',
                           sources,
                           LIBS=['geutil',
                                 'gecommon',
                                 'geqtpacket'])

env.install('tools_lib', [gecrawllib])

gecrawler = env.executable('gecrawler',
                           ['gecrawler.cpp',
                            ],
                            LIBS=['gegst', 'sgl', 'gif', env['png_ver'], 'jpeg', 'freetype', 'gecrawllib', 'geutil', 'gecommon', 'geqtpacket', 'geos', 'GL'])

geqtpdump = env.executable('geqtpdump',
                           ['geqtpdump.cpp',
                            ],
                           LIBS=['gegst', 'sgl', 'gif', env['png_ver'], 'jpeg', 'freetype', 'gecrawllib', 'geutil', 'gecommon', 'geqtpacket', 'geos', 'GL'])

env.install('tools_bin', [gecrawler,geqtpdump])
