#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')

extraObjs = [
    'fusion/autoingest/sysman/.idl/FusionUniqueId',
    ]

sources = [
    'gefConfigUtil.cpp',
    'AssetRootStatus.cpp',
    'RecoverIds.cpp',
    'FixAssetRoot.cpp',
    ]

gefconfigutil = env.sharedLib('gefconfigutil',
                              sources +
                              env.ObjFromOtherDir(extraObjs),
                              LIBS=['geautoingest', 'geconfigutil',
                                    ])

env.install('common_lib', [gefconfigutil])

# deprecating disconnected Add-On.
# env.install('disconnected_lib', [gefconfigutil])


apps = ['gefdaemoncheck',
        'geselectassetroot',
        'geupgradeassetroot',
        'geconfigureassetroot',
        ]

env.install('fusion_bin', map(lambda app:
                       env.executable(app, [app+'.cpp'],
                                      LIBS=['gefconfigutil', 'geconfigutil', 'geutil', 'gecommon', 'gemiscconfig', 'QtCore', 'QtGui',  'geautoingest', 'xerces-c', 'gexml']),
                       apps))
