#
# Copyright 2018 the Open GEE Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# -*- Python -*-
import os
Import('env')


env.testScript('bin/generate_test_asset_xmls.py')

for dir_entry in os.listdir(Dir('#/share').abspath):
    env.installRecursive(
        os.path.join(env.exportdirs['root'], 'share'),
        os.path.join('share', dir_entry))


SConscript('memory-usage-tests/SConscript', exports='env')
