#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


Import('env')
# Install the geecheck script, data files and lib files.
env.install('common_geecheck', ['geecheck/Readme.txt',
                                'geecheck/fusion_packages_3_0_0.csv',
                                'geecheck/fusion_packages_3_0_1.csv',
                                'geecheck/fusion_packages_3_1_0.csv',
                                'geecheck/fusion_packages_3_2_0.csv',
                                'geecheck/fusion_permissions_1.csv',
                                'geecheck/geecheck.pl',
                                'convert_to_kml.pl',
                                'find_terrain_pixel.pl',
                                'pg_check.pl',
                               ])
env.install('common_geecheck_lib', ['geecheck/lib/DiagnosticUtils.pm',
                                    'geecheck/lib/FileUtils.pm',
                                    'geecheck/lib/FusionServerUtils.pm',
                                    'geecheck/lib/FusionUtils.pm',
                                    'geecheck/lib/PackageUtils.pm',
                                    'geecheck/lib/PermissionUtils.pm',
                                    'geecheck/lib/SystemUtils.pm',])

env.install('httpdcgi', 'set_geecheck_config.py')
