#-*- Python -*-
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')

geprotorootgen = env.sharedLib('geprotorootgen', ['proto_dbroot_context.cc',
                                                  'proto_dbroot_generator.cc',
                                                  'proto_dbroot_combiner.cc',
                                                  'vector_dbroot_context.cc',
                                                  'vector_dbroot_generator.cc',
                                                  'raster_dbroot_context.cc',
                                                  'raster_dbroot_generator.cc'],
                            LIBS = [
                                'geautoingest',
                                'gegdal',
                                'geiconutil',
                                'gdal',
                                'geos',
                                'geutil',
                                'gecommon',
                                'QtCore', 'QtGui',
                                'gedbroot',
                                ])

gedbrootgen = env.executable('gedbrootgen',
                             ['gedbrootgen.cpp'],
                             LIBS = ['geprotorootgen',
                                     'geautoingest',
                                     'geiconutil',
                                     'geutil',
                                     'gecommon',
                                     'QtCore','QtGui',
                                     ])

gerasterdbrootgen = env.executable('gerasterdbrootgen',
                                   ['gerasterdbrootgen.cpp'],
                                   LIBS = ['geprotorootgen',
                                           'geiconutil',
                                           'geutil',
                                           'gecommon',
                                           'QtCore', 'QtGui',
                                           ])

gelayerjsgen = env.executable('gelayerjsgen',
                              ['gelayerjsgen.cpp'],
                              LIBS = ['geprotorootgen',
                                      'geautoingest',
                                      'geiconutil',
                                      'geutil',
                                      'gecommon',
                                      'QtCore','QtGui',
                                      ])

env.install('fusion_lib', [geprotorootgen])
env.install('fusion_bin', [gedbrootgen, gerasterdbrootgen, gelayerjsgen])

env.test('dbroot_generator_tests',
         ['dbroot_generator_tests.cc'],
         LIBS = ['geprotorootgen',
                 'gedbroot',
                 'geiconutil',
                 'geutil',
                 'gecommon',
                 'QtCore','QtGui',
                 'gtest',
                 ])
