# We only need a few context files, rather than the whole repository:
# --[ TST-Dockerfile: context-dir=earth_enterprise/docker/image-definition ]--

FROM centos:7

# Copy shell scripts to /root/bin in the Docker container:
RUN mkdir -p /root/opengee/bin
COPY scripts /root/opengee/bin

# Make a build directory:
RUN mkdir -p /root/opengee/build

# Install the build environment:
WORKDIR /root/opengee/build
RUN /root/opengee/bin/get-gee-build-environment.sh -y --clone-repository=no
