#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')

env.idl(['BlendStack.idl', 'VectorStack.idl', 'UnifiedConfig.idl'])

BlendStackObj = env.SharedObject('.idl/BlendStack.cpp')
VectorStackObj = env.SharedObject('.idl/VectorStack.cpp')
UnifiedConfigObj = env.SharedObject('.idl/UnifiedConfig.cpp')

geindexgen = env.executable('geindexgen',
                            ['geindexgen.cpp', 'PacketReader.cpp',
                             'Todo.cpp', 'Generator.cpp',
                             BlendStackObj, VectorStackObj],
                            LIBS=['geindex_rw', 'geindex_r', 'gexml', 'geutil', 'gecommon', 'QtCore', 'QtGui', 'xerces-c'])

geunifiedindexgen = env.executable('geunifiedindexgen',
                                   ['geunifiedindexgen.cpp',
                                    UnifiedConfigObj ],
                                   LIBS=['geindex_rw', 'geindex_r', 'gexml', 'geutil', 'gecommon', 'QtCore', 'QtGui', 'xerces-c'])

env.install('fusion_bin', [geindexgen, geunifiedindexgen])
