#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

all:
	@echo "------------------------- NOTICE -------------------------"
	@echo "The khsrc tree does not use make (or any of its variants)."
	@echo "It builds with a tool called 'scons'."
	@echo "Please see README.scons in krsrc/."
	@echo "----------------------------------------------------------"
