#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


Import('env')
import os
env = env.Clone()

portablelib_sources = ['packetbundle.cpp',
                       'packetbundle_reader.cpp',
                       'packetbundle_writer.cpp',
                       'packetbundle_finder.cpp',
                       'bounds_tracker.cpp',
                       'file_package.cpp',
                       'file_packer.cpp',
                       'file_unpacker.cpp',
                       ]

sharedportablelib = env.sharedLib('sharedportablelib', portablelib_sources, LIBS=['qtutils'])

servereader_sources = ['serverreader.cpp',
                       ]

serverreaderlib = env.sharedLib('serverreaderlib', servereader_sources,
                                LIBS=['gedbroot'])

env.install('server_lib', [serverreaderlib, sharedportablelib])

packetbundle_test = env.test('packetbundle_test',
                             ['packetbundle_unittest.cpp'],
                              LIBS=['sharedportablelib', 'gtest', 'gecommon', 'qtutils'])

file_packer_test = env.test('file_packer_test',
                            ['file_packer_unittest.cpp'],
                             LIBS=['sharedportablelib', 'gtest', 'gecommon'])

bounds_tracker_test = env.test('bounds_tracker_test',
                             ['bounds_tracker_unittest.cpp'],
                              LIBS=['sharedportablelib', 'gtest', 'gecommon', 'qtutils'])

