#!/usr/bin/env python2.7
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""All sorts of properties for every field.

Generated by ./generate-onetime-js-widget-data.py
AMD-style module definition.
Note: No leading, internal path before the [], since we'd have to hardwire it
to data/whatever-fns.js which is inflexible.
"""
# TODO: Clean up the description fields that actually contain data
# extracted from the comments of dbroot_v2.proto.

# The META_INFO contains already vetted snippets.
META_INFO = r"""
{
  "end_snippet.bbs_server_info.base_url:value": {
    "abstract_fieldpath": "end_snippet.bbs_server_info.base_url:value",
    "default_value": null,
    "description": "URL of the server including protocol, domain and port. Can be translated if we use different servers for different languages.",
    "empty_concrete_fieldpath": "end_snippet.bbs_server_info.base_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "base_url:value",
    "presence": "optional",
    "short_label": "base_url",
    "typ": "string"
  },
  "end_snippet.bbs_server_info.file_submit_path:value": {
    "abstract_fieldpath": "end_snippet.bbs_server_info.file_submit_path:value",
    "default_value": null,
    "description": "Path on server where files can be submitted.",
    "empty_concrete_fieldpath": "end_snippet.bbs_server_info.file_submit_path:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "file_submit_path:value",
    "presence": "optional",
    "short_label": "file_submit_path",
    "typ": "string"
  },
  "end_snippet.bbs_server_info.name:value": {
    "abstract_fieldpath": "end_snippet.bbs_server_info.name:value",
    "default_value": null,
    "description": "Name that will be displayed in context menu to user. Must be translated.",
    "empty_concrete_fieldpath": "end_snippet.bbs_server_info.name:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "name:value",
    "presence": "optional",
    "short_label": "name",
    "typ": "string"
  },
  "end_snippet.bbs_server_info.post_wizard_path:value": {
    "abstract_fieldpath": "end_snippet.bbs_server_info.post_wizard_path:value",
    "default_value": null,
    "description": "Path on server where wizard can be found.",
    "empty_concrete_fieldpath": "end_snippet.bbs_server_info.post_wizard_path:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "post_wizard_path:value",
    "presence": "optional",
    "short_label": "post_wizard_path",
    "typ": "string"
  },
  "end_snippet.client_options.disable_disk_cache": {
    "abstract_fieldpath": "end_snippet.client_options.disable_disk_cache",
    "default_value": null,
    "description": "If true, no data will be cached on disk for this database. It will not be accessible offline.",
    "empty_concrete_fieldpath": "end_snippet.client_options.disable_disk_cache",
    "enum_vals": null,
    "js_validation_rule": {
      "required": false
    },
    "name": "disable_disk_cache",
    "presence": "optional",
    "short_label": "disable_disk_cache",
    "typ": "bool"
  },
  "end_snippet.cobrand_info.logo_url": {
    "abstract_fieldpath": "end_snippet.cobrand_info.logo_url",
    "default_value": null,
    "description": "URL of image to use as logo. Can be remote or local. However, using local URLs depends on the installation of the client and should be used carefully.",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].logo_url",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "logo_url",
    "presence": "required",
    "short_label": "logo_url",
    "typ": "string"
  },
  "end_snippet.cobrand_info.screen_size": {
    "abstract_fieldpath": "end_snippet.cobrand_info.screen_size",
    "default_value": "0.0",
    "description": "If specified and strictly positive but <= 1.0, makes logo scalable with screen by forcing its width to occupy a fixed fraction of the screeen. For instance, a value of .25 makes the given logo occupy 25% of the screen.",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].screen_size",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "screen_size",
    "presence": "optional",
    "short_label": "screen_size",
    "typ": "double"
  },
  "end_snippet.cobrand_info.tie_point": {
    "abstract_fieldpath": "end_snippet.cobrand_info.tie_point",
    "default_value": "BOTTOM_LEFT",
    "description": "Controls reference point in overlay.",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].tie_point",
    "enum_vals": {
      "BOTTOM_CENTER": 7,
      "BOTTOM_LEFT": 6,
      "BOTTOM_RIGHT": 8,
      "MID_CENTER": 4,
      "MID_LEFT": 3,
      "MID_RIGHT": 5,
      "TOP_CENTER": 1,
      "TOP_LEFT": 0,
      "TOP_RIGHT": 2
    },
    "js_validation_rule": {
      "required": true
    },
    "name": "tie_point",
    "presence": "optional",
    "short_label": "tie_point",
    "typ": "TiePoint"
  },
  "end_snippet.cobrand_info.x_coord.is_relative": {
    "abstract_fieldpath": "end_snippet.cobrand_info.x_coord.is_relative",
    "default_value": "false",
    "description": "If true, the coordinate is relative to the screen.",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].x_coord.is_relative",
    "enum_vals": null,
    "js_validation_rule": {
      "required": false
    },
    "name": "is_relative",
    "presence": "optional",
    "short_label": "is_relative",
    "typ": "bool"
  },
  "end_snippet.cobrand_info.x_coord.value": {
    "abstract_fieldpath": "end_snippet.cobrand_info.x_coord.value",
    "default_value": "0.0",
    "description": "Coordinate value. Interpretation depends on is_relative (absolute or",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].x_coord.value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "value",
    "presence": "required",
    "short_label": "value",
    "typ": "double"
  },
  "end_snippet.cobrand_info.y_coord.is_relative": {
    "abstract_fieldpath": "end_snippet.cobrand_info.y_coord.is_relative",
    "default_value": "false",
    "description": "If true, the coordinate is relative to the screen.",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].y_coord.is_relative",
    "enum_vals": null,
    "js_validation_rule": {
      "required": false
    },
    "name": "is_relative",
    "presence": "optional",
    "short_label": "is_relative",
    "typ": "bool"
  },
  "end_snippet.cobrand_info.y_coord.value": {
    "abstract_fieldpath": "end_snippet.cobrand_info.y_coord.value",
    "default_value": "0.0",
    "description": "Coordinate value. Interpretation depends on is_relative (absolute or",
    "empty_concrete_fieldpath": "end_snippet.cobrand_info.[].y_coord.value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "value",
    "presence": "required",
    "short_label": "value",
    "typ": "double"
  },
  "end_snippet.default_web_page_intl_url:value": {
    "abstract_fieldpath": "end_snippet.default_web_page_intl_url:value",
    "default_value": null,
    "description": "Default location of web page.",
    "empty_concrete_fieldpath": "end_snippet.default_web_page_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "default_web_page_intl_url:value",
    "presence": "optional",
    "short_label": "default_web_page_intl_url",
    "typ": "string"
  },
  "end_snippet.earth_intl_url:value": {
    "abstract_fieldpath": "end_snippet.earth_intl_url:value",
    "default_value": null,
    "description": "Location of international page for earth.",
    "empty_concrete_fieldpath": "end_snippet.earth_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "earth_intl_url:value",
    "presence": "optional",
    "short_label": "earth_intl_url",
    "typ": "string"
  },
  "end_snippet.elevation_service_base_url": {
    "abstract_fieldpath": "end_snippet.elevation_service_base_url",
    "default_value": "",
    "description": "Terrain elevation service URL. If empty, service will be unavailable.",
    "empty_concrete_fieldpath": "end_snippet.elevation_service_base_url",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "elevation_service_base_url",
    "presence": "optional",
    "short_label": "elevation_service_base_url",
    "typ": "string"
  },
  "end_snippet.hide_user_data": {
    "abstract_fieldpath": "end_snippet.hide_user_data",
    "default_value": "false",
    "description": "If true, hides user license key in about dialog. Useful for Pro only, allows information to not be visible for shared license keys.",
    "empty_concrete_fieldpath": "end_snippet.hide_user_data",
    "enum_vals": null,
    "js_validation_rule": {
      "required": false
    },
    "name": "hide_user_data",
    "presence": "optional",
    "short_label": "hide_user_data",
    "typ": "bool"
  },
  "end_snippet.keyboard_shortcuts_url:value": {
    "abstract_fieldpath": "end_snippet.keyboard_shortcuts_url:value",
    "default_value": null,
    "description": "URL for keyboard shortcuts page. If not specified, this URL is built from user_guide_intl_url as user_guide_intl_url + \"ug_keyboard.html\".",
    "empty_concrete_fieldpath": "end_snippet.keyboard_shortcuts_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "keyboard_shortcuts_url:value",
    "presence": "optional",
    "short_label": "keyboard_shortcuts_url",
    "typ": "string"
  },
  "end_snippet.model.compressed_negative_altitude_threshold": {
    "abstract_fieldpath": "end_snippet.model.compressed_negative_altitude_threshold",
    "default_value": null,
    "description": "Threshold below which negative altitudes are compressed",
    "empty_concrete_fieldpath": "end_snippet.model.compressed_negative_altitude_threshold",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "compressed_negative_altitude_threshold",
    "presence": "optional",
    "short_label": "compressed_negative_altitude_threshold",
    "typ": "double"
  },
  "end_snippet.model.elevation_bias": {
    "abstract_fieldpath": "end_snippet.model.elevation_bias",
    "default_value": null,
    "description": "Elevation bias",
    "empty_concrete_fieldpath": "end_snippet.model.elevation_bias",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "elevation_bias",
    "presence": "optional",
    "short_label": "elevation_bias",
    "typ": "double"
  },
  "end_snippet.model.flattening": {
    "abstract_fieldpath": "end_snippet.model.flattening",
    "default_value": "0.00335281066474748",
    "description": "Planet flattening. Default value is 1.0/298.257223563 (from  WGS84).",
    "empty_concrete_fieldpath": "end_snippet.model.flattening",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "flattening",
    "presence": "optional",
    "short_label": "flattening",
    "typ": "double"
  },
  "end_snippet.model.negative_altitude_exponent_bias": {
    "abstract_fieldpath": "end_snippet.model.negative_altitude_exponent_bias",
    "default_value": null,
    "description": "Bias for negative altitude so that ocean tiles can be streamed to older clients",
    "empty_concrete_fieldpath": "end_snippet.model.negative_altitude_exponent_bias",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "negative_altitude_exponent_bias",
    "presence": "optional",
    "short_label": "negative_altitude_exponent_bias",
    "typ": "int32"
  },
  "end_snippet.model.radius": {
    "abstract_fieldpath": "end_snippet.model.radius",
    "default_value": "6378.13700",
    "description": "Mean planet radius. Default value is the WGS84 model for earth.",
    "empty_concrete_fieldpath": "end_snippet.model.radius",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "radius",
    "presence": "optional",
    "short_label": "radius",
    "typ": "double"
  },
  "end_snippet.privacy_policy_url:value": {
    "abstract_fieldpath": "end_snippet.privacy_policy_url:value",
    "default_value": null,
    "description": "URL for the privacy policy.",
    "empty_concrete_fieldpath": "end_snippet.privacy_policy_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "privacy_policy_url:value",
    "presence": "optional",
    "short_label": "privacy_policy_url",
    "typ": "string"
  },
  "end_snippet.release_notes_url:value": {
    "abstract_fieldpath": "end_snippet.release_notes_url:value",
    "default_value": null,
    "description": "URL for release notes page.",
    "empty_concrete_fieldpath": "end_snippet.release_notes_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "release_notes_url:value",
    "presence": "optional",
    "short_label": "release_notes_url",
    "typ": "string"
  },
  "end_snippet.reverse_geocoder_protocol_version": {
    "abstract_fieldpath": "end_snippet.reverse_geocoder_protocol_version",
    "default_value": "3",
    "description": "Reverse geocoder protocol version. Default is 3 which is the protocol supported by newer clients.",
    "empty_concrete_fieldpath": "end_snippet.reverse_geocoder_protocol_version",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "reverse_geocoder_protocol_version",
    "presence": "optional",
    "short_label": "reverse_geocoder_protocol_version",
    "typ": "int32"
  },
  "end_snippet.reverse_geocoder_url:value": {
    "abstract_fieldpath": "end_snippet.reverse_geocoder_url:value",
    "default_value": null,
    "description": "Reverse geocoder server URL",
    "empty_concrete_fieldpath": "end_snippet.reverse_geocoder_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "reverse_geocoder_url:value",
    "presence": "optional",
    "short_label": "reverse_geocoder_url",
    "typ": "string"
  },
  "end_snippet.show_signin_button": {
    "abstract_fieldpath": "end_snippet.show_signin_button",
    "default_value": null,
    "description": "If true, shows the signin button in the upper right corner.",
    "empty_concrete_fieldpath": "end_snippet.show_signin_button",
    "enum_vals": null,
    "js_validation_rule": {
      "required": false
    },
    "name": "show_signin_button",
    "presence": "optional",
    "short_label": "show_signin_button",
    "typ": "bool"
  },
  "end_snippet.startup_tips_intl_url:value": {
    "abstract_fieldpath": "end_snippet.startup_tips_intl_url:value",
    "default_value": null,
    "description": "URL from which to load startup tips in Earth 7.0 and higher.",
    "empty_concrete_fieldpath": "end_snippet.startup_tips_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "startup_tips_intl_url:value",
    "presence": "optional",
    "short_label": "startup_tips_intl_url",
    "typ": "string"
  },
  "end_snippet.support_answer_intl_url:value": {
    "abstract_fieldpath": "end_snippet.support_answer_intl_url:value",
    "default_value": null,
    "description": "Url to support answer.",
    "empty_concrete_fieldpath": "end_snippet.support_answer_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "support_answer_intl_url:value",
    "presence": "optional",
    "short_label": "support_answer_intl_url",
    "typ": "string"
  },
  "end_snippet.support_center_intl_url:value": {
    "abstract_fieldpath": "end_snippet.support_center_intl_url:value",
    "default_value": null,
    "description": "Url to support center.",
    "empty_concrete_fieldpath": "end_snippet.support_center_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "support_center_intl_url:value",
    "presence": "optional",
    "short_label": "support_center_intl_url",
    "typ": "string"
  },
  "end_snippet.support_request_intl_url:value": {
    "abstract_fieldpath": "end_snippet.support_request_intl_url:value",
    "default_value": null,
    "description": "Url to support pages.",
    "empty_concrete_fieldpath": "end_snippet.support_request_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "support_request_intl_url:value",
    "presence": "optional",
    "short_label": "support_request_intl_url",
    "typ": "string"
  },
  "end_snippet.support_topic_intl_url:value": {
    "abstract_fieldpath": "end_snippet.support_topic_intl_url:value",
    "default_value": null,
    "description": "Url to support topics used by certain diagnostic messages.",
    "empty_concrete_fieldpath": "end_snippet.support_topic_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "support_topic_intl_url:value",
    "presence": "optional",
    "short_label": "support_topic_intl_url",
    "typ": "string"
  },
  "end_snippet.swoop_parameters.start_dist_in_meters": {
    "abstract_fieldpath": "end_snippet.swoop_parameters.start_dist_in_meters",
    "default_value": null,
    "description": "Controls how far from a target swooping should start.",
    "empty_concrete_fieldpath": "end_snippet.swoop_parameters.start_dist_in_meters",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "start_dist_in_meters",
    "presence": "optional",
    "short_label": "start_dist_in_meters",
    "typ": "double"
  },
  "end_snippet.tutorial_url:value": {
    "abstract_fieldpath": "end_snippet.tutorial_url:value",
    "default_value": null,
    "description": "URL for tutorial page. If not specified, this URL is built from user_guide_intl_url as user_guide_intl_url + \"tutorials/index.html\".",
    "empty_concrete_fieldpath": "end_snippet.tutorial_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "tutorial_url:value",
    "presence": "optional",
    "short_label": "tutorial_url",
    "typ": "string"
  },
  "end_snippet.use_ge_logo": {
    "abstract_fieldpath": "end_snippet.use_ge_logo",
    "default_value": "true",
    "description": "If false, hides the Google logo.",
    "empty_concrete_fieldpath": "end_snippet.use_ge_logo",
    "enum_vals": null,
    "js_validation_rule": {
      "required": false
    },
    "name": "use_ge_logo",
    "presence": "optional",
    "short_label": "use_ge_logo",
    "typ": "bool"
  },
  "end_snippet.user_guide_intl_url:value": {
    "abstract_fieldpath": "end_snippet.user_guide_intl_url:value",
    "default_value": null,
    "description": "Url to user guide.",
    "empty_concrete_fieldpath": "end_snippet.user_guide_intl_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "user_guide_intl_url:value",
    "presence": "optional",
    "short_label": "user_guide_intl_url",
    "typ": "string"
  },
  "end_snippet.valid_database.database_name:value": {
    "abstract_fieldpath": "end_snippet.valid_database.database_name:value",
    "default_value": null,
    "description": "Human-readable name of database (such as \"Primary Database\" or \"Digital Globe Database\")",
    "empty_concrete_fieldpath": "end_snippet.valid_database.[].database_name:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "database_name:value",
    "presence": "optional",
    "short_label": "database_name",
    "typ": "string"
  },
  "end_snippet.valid_database.database_url": {
    "abstract_fieldpath": "end_snippet.valid_database.database_url",
    "default_value": null,
    "description": "URL of server. This can include a path and query, and must be a well-formed, absolute URL.",
    "empty_concrete_fieldpath": "end_snippet.valid_database.[].database_url",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "database_url",
    "presence": "required",
    "short_label": "database_url",
    "typ": "string"
  },
  "end_snippet.search_config.error_page_url:value": {
    "abstract_fieldpath": "end_snippet.search_config.error_page_url:value",
    "default_value": "about:blank",
    "description": "URL of a page that will be displayed if a network error or other local error occurs while performing a search.  This might be an error for a local geocode while in offline mode, a connection error while trying to connect to MFE, or some other error where we can't get an error message from the server.  (Obviously this page should be cached locally, or it's not terribly useful.)  The URL should be fully encoded, and can use $[hl] and friends if necessary.",
    "empty_concrete_fieldpath": "end_snippet.search_config.error_page_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "error_page_url:value",
    "presence": "optional",
    "short_label": "error_page_url",
    "typ": "string"
  },
  "end_snippet.search_config.kml_render_url:value": {
    "abstract_fieldpath": "end_snippet.search_config.kml_render_url:value",
    "default_value": "/earth/client/kmlrender/index_$[hl].html",
    "description": "URL of a page that will be shown when KML is rendered in the search panel. This page should have JavaScript that reads the KML from the environment and renders it as HTML, but should NOT perform onebox or searchlet searches. The URL should be fully encoded, and can use $[hl] and friends if necessary.",
    "empty_concrete_fieldpath": "end_snippet.search_config.kml_render_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "kml_render_url:value",
    "presence": "optional",
    "short_label": "kml_render_url",
    "typ": "string"
  },
  "end_snippet.search_config.kml_search_url:value": {
    "abstract_fieldpath": "end_snippet.search_config.kml_search_url:value",
    "default_value": "/earth/client/kmlrender/index_$[hl].html",
    "description": "URL of a page that will be shown when a KML search is performed. This page should have JavaScript that reads the KML from the environment and renders it as HTML, and also performs onebox and searchlet searches if applicable. The URL should be fully encoded, and can use $[hl] and friends if necessary.",
    "empty_concrete_fieldpath": "end_snippet.search_config.kml_search_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "kml_search_url:value",
    "presence": "optional",
    "short_label": "kml_search_url",
    "typ": "string"
  },
  "end_snippet.search_config.search_history_url:value": {
    "abstract_fieldpath": "end_snippet.search_config.search_history_url:value",
    "default_value": "http://www.google.com/earth/client/search/history_$[hl].html",
    "description": "URL of a page that will be shown when the search history is requested. This page should have JavaScript that reads the search history from the client and renders it as HTML.",
    "empty_concrete_fieldpath": "end_snippet.search_config.search_history_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "search_history_url:value",
    "presence": "optional",
    "short_label": "search_history_url",
    "typ": "string"
  },
  "end_snippet.google_maps_url:value": {
    "abstract_fieldpath": "end_snippet.google_maps_url:value",
    "default_value": "",
    "description": "URL for Google Maps, for features like 'View in Maps'.",
    "empty_concrete_fieldpath": "end_snippet.google_maps_url:value",
    "enum_vals": null,
    "js_validation_rule": {
      "required": true
    },
    "name": "google_maps_url:value",
    "presence": "optional",
    "short_label": "google_maps_url",
    "typ": "string"
  }
}
"""
