#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')

env = env.Clone()
env.Append( CXXFLAGS = ['-Wno-unused-function', '-Wno-unused-value', '-DQT3_SUPPORT'],
            CPPPATH = ['#fusion/mtjtools/histogram'])

hmocfiles = [ 'application.h' ]
qtcpps = env.qtFiles([], hmocfiles, [], '')
qtobjs = map(lambda f: env.StaticObject(f), qtcpps)


scroll = env.executable('scroll',
                        ['main.cpp',
                         'imageview.cpp',
                         'linreg.cpp',
                         'application.cpp'
                         ] + qtobjs,
                        LIBS=['gehistogram', 'gdal', 'geutil', 'gecommon', 'QtCore', 'QtGui', 'Qt3Support', 'geos'])

env.install('tools_bin', [scroll])
