#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#-*- Python -*-
Import('env')

env.install('fusion_root', [ 'ge-fusion.csh', 'ge-fusion.sh'], 'etc/profile.d')
env.install('server_root', [ 'ge-server.csh', 'ge-server.sh'], 'etc/profile.d')

sources = [ 'geCapabilities.cpp',
            'gePrompt.cpp',
            'geConfigUtil.cpp',
            ]

geconfigutil = env.sharedLib('geconfigutil', sources,
                             LIBS=['geutil',
                                   'cap',   # system capabilties library
                                   ])

env.install('common_lib', [geconfigutil])
