version: "3"
services:
  web:
    image: opengee-experimental:latest
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
    cap_add:
      - DAC_READ_SEARCH
    ports:
      - "80:80"
    volumes:
      - "/gevol:/gevol"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
