#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""SConscript for khgdal."""
Import('env')

env.idl(['khVirtualRaster.idl'])
gegdal = env.sharedLib('gegdal', ['khgdal.cpp',
                                  'khGeoExtents.cpp',
                                  'khGDALDataset.cpp',
                                  'khGDALImage.cpp',
                                  'khGDALBuffer.cpp',
                                  'khVRDataset.cpp',
                                  '.idl/khVirtualRaster.cpp',
                                  'khGDALReader.cpp',
                                 ],
                       LIBS=['gexml', 'gdal', 'QtCore','QtGui', 'gecommon', 'geutil'])

gegdalutil = env.sharedLib('gegdalutil', ['RasterClusterAnalyzer.cpp'],
                           LIBS=['gegdal', 'gecommon'])


geinfo = env.executable('geinfo', 'geinfo.cpp',
                        LIBS=['gegdal', 'geraster', 'geindex_rw',
                              'geqtpacket', 'geindex_r', 'geutil', 'gecommon', 'gdal', 'QtCore','QtGui', 'geos'])

gevirtualraster = env.executable('gevirtualraster', ['gevirtualraster.cpp'],
                                 LIBS=['gegdal', 'gegdalutil', 'geutil', 'gecommon', 'gdal', 'QtCore','QtGui', 'geos'])

geupdatelut = env.executable('geupdatelut', 'geupdatelut.cpp',
                             LIBS=['gegdal', 'geutil', 'gecommon', 'gdal', 'QtCore','QtGui', 'geos'])

gesplitkhvr = env.executable('gesplitkhvr', 'gesplitkhvr.cpp',
                             LIBS=['gegdal', 'geutil', 'gecommon', 'QtCore','QtGui', 'geos'])

khprepvirtrast = env.executable('khprepvirtrast', 'khprepvirtrast.cpp',
                                LIBS=['gegdal', 'geutil', 'gecommon', 'gdal', 'QtCore','QtGui', 'geos'])
getranslate = env.executable('getranslate', 'getranslate.cpp',
                             LIBS=['gegdal', 'gdal', 'geos'])
gereproject = env.executable('gereproject', 'gereproject.cpp',
                             LIBS=['gegdal', 'geutil', 'gdal', 'geos'])

khgdal_test = env.test('khgdal_test',
    ['khgdal_test.cpp'],
    LIBS=['gegdal', 'gecommon', 'gdal', 'geos', 'gtest', 'dl'])

khGDALReader_unittest = env.test('khGDALReader_unittest',
    ['khGDALReader_unittest.cpp'],
    LIBS=['gegdal', 'gecommon', 'geos', 'gtest'])

env.install('fusion_bin', [geinfo, gevirtualraster, gesplitkhvr,
                           getranslate, gereproject])
env.install('tools_bin', [geupdatelut, khprepvirtrast])
env.install('fusion_lib', [gegdal, gegdalutil])

env.test('khGDALDataset_unittest',
          'khGDALDataset_unittest.cpp',
          LIBS=['gegdal', 'gdal', 'gecommon', 'gtest'])
