// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#include <cstdint>
#include <string>
#include <vector>

class StartJobMsg {
  std::uint32_t jobid;
  std::string logfile;
  std::vector<std::vector<std::string> > commands;

#pragma StrLoadAndSave
};

class StopJobMsg {
  std::uint32_t jobid;

#pragma StrLoadAndSave
};

class JobProgressMsg {
  std::uint32_t jobid;
  std::uint32_t beginTime;
  std::uint32_t progressTime;
  double progress;

#pragma StrLoadAndSave
};

class JobDoneMsg {
  std::uint32_t jobid;
  bool   success;
  std::uint32_t beginTime;
  std::uint32_t endTime;

#pragma StrLoadAndSave
};

class ProviderConnectMsg {
  std::string host;
  unsigned int        numCPUs;
  std::string fusionVer = std::string();

#pragma StrLoadAndSave
};
