// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <map>
#include <autoingest/.idl/storage/MapSubLayerConfig.h>

#cppquote
#include <autoingest/.idl/storage/MapSubLayerConfig_impl.h>
#include <autoingest/.idl/storage/AssetDefs.h>
#include <autoingest/geAssetRoot.h>
#include <khFileUtils.h>
#/cppquote

class MapTextStyleSet
{
  std::map<unsigned int, MapTextStyleConfig> configs;

#pragma LoadAndSave

#hquote
  static std::string Filename(void);
  bool Load(void);
  bool Save(void);
#/hquote

#cppquote
  std::string
  MapTextStyleSet::Filename(void)
  {
    return khComposePath(geAssetRoot::Dirname(AssetDefs::AssetRoot(),
                                              geAssetRoot::UserDataDir),
                         "maptextstyles.xml");
  }

  bool
  MapTextStyleSet::Load(void)
  {
    std::string filename = Filename();
    if (!khExists(filename)) {
      // missing file means empty, it's not an error
      return true;
    }

    return Load(filename.c_str());
  }

  bool
  MapTextStyleSet::Save(void)
  {
    std::string filename = Filename();
    if (Save(filename)) {
      khChmod(filename, 0666); // in case the umask trimmed any permissions
      return true;
    } else {
      return false;
    }
  }
#/cppquote

};
