#!/bin/bash
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

STREAM_SERVER_URL=""
SEARCH_SERVER_URL=""
STREAM_VS=""
SEARCH_VS=""

BINDIR=/opt/google/bin
CMD=$BINDIR/geserveradmin


if [ ! -n "$1" ]
then
  echo "Usage: gedisconnectedpublish <db_name> <dbalias>";
  exit 1;
fi

db_name=$1;
pretty_name=$db_name;

if [ -n "$2" ]
then
  pretty_name=$2;
fi

if [ -n "$STREAM_SERVER_URL" ]
then
  CMD="$CMD --stream_server_url $STREAM_SERVER_URL";
fi

if [ -n "$SEARCH_SERVER_URL" ]
then
  CMD="$CMD --search_server_url $SEARCH_SERVER_URL";
fi

######################     ADDD    #######################
# echo "Executing $CMD --adddb $db_name --dbalias $pretty_name";
$CMD --adddb $db_name --dbalias $pretty_name;
ret_val=$?;

if [ $ret_val != 0 ]
then
  exit 1;
fi

###################   PUSH/PUBLISH    ########################

if [ -n "$STREAM_VS" ]
then
  CMD="$CMD --streamvs $STREAM_VS";
fi

if [ -n "$SEARCH_VS" ]
then
  CMD="$CMD --searchvs $SEARCH_VS";
fi


# echo "Executing $CMD --publishdb $db_name --push";
$CMD --publishdb $db_name --push;


