#!/bin/bash
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Startup script for Google Earth Server.

### BEGIN INIT INFO
# Provides: geserver
# Required-Start: nscd
# Should-Start:
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:    Startup script for Google Earth Server.
### END INIT INFO

if [ "$EUID" != "0" ] ; then
  echo `basename $0` "must be run as root"
  exit 1;
fi

# Fix the hostname to equal hostname -f
hostname_f=`hostname -f`
`hostname $hostname_f`

# Installer will overwrite the IA_* macros (e.g., IA_GEAPACHE_USER)
# with the user-specified values.
# As of 3.1, GEE Fusion and GEE Server supports custom usernames which are
# specified at install time.
#"geapacheuser"
GEAPACHEUSER="IA_GEAPACHE_USER"
#"gepguser"
GEPGUSER="IA_GEPGUSER"

prog=geserver
gehttpd_root=/opt/google/gehttpd/bin
gebin_root=/opt/google/bin
dashes='--------------------------------------------------------------------'

# Variable where result of start/stop are stored for later return by
# this script
RETVAL=0

use_su=`su $GEPGUSER -c "echo -n 1" 2>/dev/null || echo -n 0`

run_as_user() {
  if [ $use_su -eq 1 ] ; then
    ( cd / ;su $1 -c "$2" )
  else
    ( cd / ;sudo -u $1 bash -c "$2" )
  fi
}

start() {
  echo $dashes
  run_as_user $GEPGUSER "$gebin_root/pg_ctl -D /var/opt/google/pgsql/data -l /var/opt/google/pgsql/logs/pg.log start -w";
  echo
  echo $dashes
  $gehttpd_root/gehttpd_init start
  echo
  echo $dashes
  echo 'Done Starting Google Earth Enterprise Server'
  echo
}

stop() {
  echo $"Stopping $prog: "
  echo
  echo $dashes
  $gehttpd_root/gehttpd_init stop
  echo
  echo $dashes
  # only stop if already running...
  if [ -f /var/opt/google/pgsql/data/postmaster.pid ] ; then
    run_as_user $GEPGUSER "$gebin_root/pg_ctl -D /var/opt/google/pgsql/data -l /var/opt/google/pgsql/logs/pg.log stop";
    rm -f /var/opt/google/pgsql/data/postmaster.pid
  fi
  echo $dashes
  echo 'Done Stopping Google Earth Enterprise Server'
  echo
}

# See how we were called.
case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart)
  stop
  sleep 1
  start
  ;;
  *)
  echo $"Usage: $prog {start|stop|restart}"
  exit 1
esac

exit $RETVAL

