#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


Import('env')


# pick up the regular subdirs
env = env.Clone();
env.Append(CPPPATH = ['#server'])

# Install password file for admin access.
env.install('httpdconf', ['.htpasswd'])

# Install the postgres init script along with the sql files.
env.install('server_bin', ['geresetpgdb', 'gepgcommon'])
env.install('server_sql', ['examplesearch.sql', 'examplesearch_2delete.sql',
  'examplesearch_delete.sql', 'gestream_tables.sql',
  'gestream_tables_upgrade_to_3_1.sql', 'gesearch_tables.sql',
  'geendsnippet_tables.sql'])
env.install('httpd', ['gehttpd_init'], 'bin')
env.install('server_bin', ['geconfigurepublishroot', 'geselectpublishroot'])

# deprecated.
# env.install('disconnected_bin', ['gedisconnectedpublish'])

# Install the geserver restart script under etc/init.d
env.install('server_root', [ 'geserver' ], 'etc/init.d')

gerestartapache = env.executable('gerestartapache', 'gerestartapache.cpp',
                            LIBS=[])
env.install('server_bin', [gerestartapache])

env.install('server_bin', ['gecutter'])


# now make a special env from compiling apache modules & pick them up
# XXX - the CPPFLAGS need to vary by platform
# XXX - need to add local user dir overrides
env = env.Clone(SHLIBPREFIX = '');  # we want mod_*.so not libmod_*.so
env.Append( CPPFLAGS = ['-DSHARED_MODULE',
                       '-DLINUX=2',
                       '-DUSE_HSREGEX',
                       '-DUSE_EXPAT',
                       '-DEAPI',
                      ],
)

SConscript('mod_fdb/SConscript', exports='env')
SConscript('icons/SConscript', exports='env')
SConscript('wsgi/SConscript', exports='env')
