#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import sys
import os
import commands         # TODO: This has been deprecated since 2.6 (?)

env = Environment()

# process commandline arguments
installdir = ARGUMENTS.get('installdir', 0)

# this fallback really shouldn't be used, whenever you specify the install
# target you should also specify an install dir.
# But having a default makes the rest of the SCons code easier
if (not installdir) and ('install' in COMMAND_LINE_TARGETS):
   print "installdir=... must be specified with install target"
   Exit(1)

tutorials_dir = installdir + '/tutorial'
root_dir = tutorials_dir + '/opt/google/share/tutorials/fusion/'

# Get the current directory, since SCons will move into the directory
#   it's using, and FusionTutorial is expected below the SConscript file.
tutorial_src_dir = os.path.join(os.getcwd(), 'FusionTutorial')

def copyFiles(dest_dir, src_dir):
    """Make copies of all files in src_dir and place
    them in dest_dir. Recurse through all subdirectories 
    of src_dir.
    """
    # Strip trailing slashes because they cause trouble later
    dest_dir = dest_dir.rstrip(os.sep)
    src_dir = src_dir.rstrip(os.sep)
    # Ensure the destination directory exists at each step
    commands.getstatusoutput("mkdir -p " + dest_dir)
    commands.getstatusoutput("cp -R " + src_dir + os.sep 
                             + "*" + " " + dest_dir)

# Clean install dir (note: the current sconscripts leave stuff behind, like
# directories).
if env.GetOption('clean'):
    # clean the search and getomcat install folders.
    commands.getstatusoutput("rm -rf " + tutorials_dir)
else:
    copyFiles(root_dir, tutorial_src_dir)

