#-*- Python -*-
# Copyright 2008 Google Inc. All Rights Reserved.
# Author markwheeler 2008-09-15

import os
Import('env')

# Install manual to /opt/google/share/doc.
env.install('manual_share', 'landing_page/manual', 'doc/')

# Install previous Fusion versions documentation to /opt/google/share/doc.
env.install('fusion_share',
            'landing_page/previous_fusion_versions',
            'doc/')
