#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#-*- Python -*-

Import('env')
import os

serverdb = env.sharedLib('serverdb', ['serverdb.cpp'],
                       LIBS=[])

serverdb_r = env.sharedLib('serverdb_r', ['serverdbReader.cpp', 'map_tile_utils.cpp'],
                           LIBS=['serverdb', 'geindex_r', 'gedbroot',
                                 'gecommon', 'keyholeutils', env['png_ver']])

env.install('common_lib', [serverdb, serverdb_r])

# Note: server_db is in common_lib, so it will be bundled to both Server and
# Fusion installer.
# env.install('disconnected_lib', [serverdb])

env.test('serverdbReader_unittest',
         'serverdbReader_unittest.cpp',
         LIBS=['serverdb_r', 'gecommon', 'QtGui', 'QtCore', env['png_ver']])
