// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#include <cstdint>
#include <string>
#include <vector>
#include <searchtabs/.idl/SearchTabs.h>
#requiresgetheapusage

#cppquote
#include <searchtabs/.idl/SearchTabs_impl.h>
#/cppquote

class GEDBAssetConfig {
  std::string index_verref_;
  std::string vector_project_;
  std::string imagery_project_;
  std::string terrain_project_;
  // TODO: deprecate search_tabs_.
  std::vector<SearchTabDefinition> search_tabs_;
  unsigned int database_version_;
  deprecated bool search_tabs_enabled_ = true;
  deprecated std::string fusion_version_ = std::string();

// To force rebuilds, increment this version.
// When incrementing this version, you should also increment the
// one in Database so this one gets the chance to get checked.
#version 2
// 1 -> gedbrootgen changed to emit protobuf dbroot instead of ETA dbroot
// (targeted for 5.0).
// 2 -> gedbgen changed to set proto_imagery to true in time-machine protobuf
// dbroot (targeted for 5.1.1).

#pragma GenerateIsUpToDate
};
