// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#include <cstdint>
#include <string>
#include <vector>
#include <khMetaData.h>
#include <searchtabs/.idl/SearchTabs.h>
#include <autoingest/.idl/storage/SearchTabReference.h>
#requiresgetheapusage

#cppquote
#include <searchtabs/.idl/SearchTabs_impl.h>
#include <autoingest/.idl/storage/SearchTabReference_impl.h>
#/cppquote


class MapDatabaseConfig {
  std::string imageryProject;
  std::string mapProject;

  IsUpToDateIgnore unsigned int indexVersion = uint(1);
  deprecated bool searchTabsEnabled = false;

  // TODO: deprecate search_tabs_, search_tab_refs_.
  // will be empty in asset, but populated in version
  std::vector<SearchTabDefinition> search_tabs_ = std::vector<SearchTabDefinition>();

  // will be populated in asset, but empty in version
  std::vector<SearchTabReference> search_tab_refs_ = std::vector<SearchTabReference>();

  bool useGoogleImagery = false;
  bool is_mercator = false;

#pragma GenerateIsUpToDate

#hquote

 public:
  // Resets all Ids as it is in a config for just created asset.
  void ResetIds(void) {
    indexVersion = 1;
  }
#/hquote
};


class MapDatabaseEditRequest {
  std::string assetname;
  MapDatabaseConfig config;
  khMetaData meta;

#pragma StrLoadAndSave
};
