// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#include <cstdint>
#include <string>
#include <vector>
#include <khInsetCoverage.h>
#requiresgetheapusage

class PacketGenConfig {
#pragma DontEmitDefaults

  // Leave it as a class (don't just make insets a vector of string). That
  // way if later we need to store more information for each inset, we have
  // a place to put it that won't break old ones.
  class Inset {
#pragma DontEmitDefaults

    std::string rasterProductVersion;
    std::string packgenVersion = std::string();
#pragma GenerateIsUpToDate
  };

  std::vector<Inset> insets;
  khInsetCoverage coverage;
  unsigned int            beginMinifyLevel;
  unsigned int            endMinifyLevel;
  bool            cacheRaster;

  // > maxlevel -> don't simplify
  unsigned int            beginSimplifyLevel = uint(100);
  unsigned int            beginSkipTransparentLevel = uint(100);

  // if the top inset has opaque tiles at the target level, use them
  // instead of merging.
  bool            useOpaqueTopInsetInsteadOfMerge = false;

  // add(or not) separate alpha_image into imagery-packet.
  deprecated bool            separate_alpha_ = true;


  // Note: Basic rule for #version: "If the low level tool ever
  // changes to produce different output from the same config record, then
  // the version of its config needs to be increased as well as the versions
  // of all the containing configs all the way up the plugin hierarchy."

  // To force rebuilds, increment this version.
  // When incrementing this version, you should also increment the
  // one in RasterProject so this one gets the chance to get checked.
// #version 1
  // 1 -> gepackgen changed to emit protobuf imagery instead of ETA imagery
  // for Earth's DB and imagery with alpha in 4-channel PNG for Map's DB
  // (targeted for 5.0).
  // version commented -> Note: version number reverted back to
  // switch off force rebuild for imagery project (targeted to 5.0.0).

#pragma GenerateIsUpToDate
};
