// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//

#include <cstdint>
#include <string>
#include <vector>
#include <map>
#requiresgetheapusage

// ****************************************************************************
// ***  RasterGEIndex
// ****************************************************************************
class RasterPacketLevelVersion {
  // cannot pre-bind this to a packetfile output name, since this config
  // gets built before all the packetlevels are completed
  std::string packet_level_verref_;
  unsigned int index_version_;
#pragma GenerateIsUpToDate
};
class RasterPacketInset {
  std::vector<RasterPacketLevelVersion> levels_;
#pragma GenerateIsUpToDate
}
class RasterGEIndexConfig {
  std::string db_name_;
  IsUpToDateIgnore unsigned int index_version_;
  std::vector<RasterPacketInset> packet_insets_;
  std::string date_string_ = std::string("");
#pragma GenerateIsUpToDate
};
