// Copyright 2017 Google Inc.
// Copyright 2020 The Open GEE Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <cstdint>
#include <string>
#include <vector>
#include <map>
#include <autoingest/.idl/storage/DatedImageryIndexInfo.h>
#include <autoingest/.idl/storage/DatedImageryIndexInfo_impl.h>

#cppquote
#include <autoingest/.idl/storage/DatedImageryIndexInfo_impl.h>
#/cppquote

class geqtgen::Config {
  unsigned int        index_version_;
  std::string imagery_index_;
  std::string terrain_index_;
  std::string vector_index_;
  unsigned int        terrain_packet_version_ = uint(0);

  typedef std::map<std::uint32_t,std::uint32_t> ProviderMap;
  std::map<std::uint32_t,std::uint32_t> inset_provider_map_ = geqtgen::Config::ProviderMap();

  // Acquisition date of the imagery project.
  std::string imagery_date_string_ = std::string();

  // Optional list of "TimeMachine" Imagery Indexes that are served by date.
  std::vector<DatedImageryIndexInfo> dated_imagery_indexes_ = std::vector<DatedImageryIndexInfo>();

#pragma LoadAndSave
};
