#!/usr/bin/env python2.7
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
This is modified setup.py script generated by py2applet.

The modifications are for associating the glb file with
the application.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['globe_selector.py']
DATA_FILES = []

Plist = dict(
             CFBundleName               = "globe_selector",
             CFBundleShortVersionString = "0.1.0",
             CFBundleGetInfoString      = "globe_selector 0.1.0",
             CFBundleExecutable         = "globe_selector",
             CFBundleIdentifier         = "com.google.globe_selector",
             CFBundleDocumentTypes      = [dict(CFBundleTypeExtensions=["glb"],
                                                CFBundleTypeIconFile='gme_glb',
                                                CFBundleTypeName="GEE Portable Globe",
                                                CFBundleTypeRole="Viewer"),
                                           dict(CFBundleTypeExtensions=["glc"],
                                                CFBundleTypeIconFile='gme_glc',
                                                CFBundleTypeName="GEE Portable Composite",
                                                CFBundleTypeRole="Viewer"),
                                           dict(CFBundleTypeExtensions=["glm"],
                                                CFBundleTypeIconFile='gme_glm',
                                                CFBundleTypeName="GEE Portable Map",
                                                CFBundleTypeRole="Viewer"),
                                           ], LSUIElement = True,
             )

OPTIONS = {'argv_emulation': True,
           'iconfile': 'icons/portable_server.icns',
           'plist': Plist,
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
