#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')

env.idl(['DBConfig.idl'])

DBConfigObj = env.SharedObject('.idl/DBConfig.cpp')

gedbgen = env.executable('gedbgen',
                         ['gedbgen.cpp', DBConfigObj],
                         LIBS=['geprotorootgen', 'geautoingest', 'gesearchtabs',
                               'gexml', 'gedbroot', 'geiconutil', 'geutil', 'gecommon',
                               'dbmanifest', 'QtCore', 'QtGui', 'xerces-c'])

mapdbgen = env.executable('mapdbgen',
                          ['mapdbgen.cpp', DBConfigObj],
                          LIBS=['geautoingest', 'gesearchtabs',
                                'gexml', 'geutil', 'gecommon',
                                'dbmanifest', 'QtCore', 'QtGui', 'xerces-c'])

env.install('fusion_bin', [gedbgen, mapdbgen])
