google.maps.__gjsload__('visualization_impl', function(_){var D6=function(a,b,c){if(!C6){for(var d=Array(256),e=0;256>e;++e){for(var f=e,g=0;8>g;++g)f=f&1?(3988292384^f>>>1)>>>0:f>>>1;d[e]=f}C6=d}d=4294967295;e=b;for(b+=c;e<b;++e)d=(C6[(d^a[e])&255]^d>>>8)>>>0;return(d^4294967295)>>>0},E6=function(a){for(var b=Array(a),c=0;c<a;++c)b[c]=0;for(var c=Array(a),d=0;d<a;++d)c[d]=b.concat();return c},F6=function(a){if(!a||!a.getLength())return 1;var b=new _.Sd;a.forEach(function(a){a&&b.extend(a.location||a)});var c=b.f.f,d=b.b.b,e=Math.max(b.f.b-c,b.b.f-d);if(1E-9>
e){var f=0;a.forEach(function(a){a instanceof _.P?++f:f+=a.weight});return Math.max(1,f)}var g=800/e,h=E6(800),l=1;a.forEach(function(a){if(a){var b=a.location||a;a=a.weight||1;b=new _.N(Math.max(0,Math.min(799,Math.floor((b.lat()-c)*g))),Math.max(0,Math.min(799,Math.floor((b.lng()-d)*g))));h[b.x][b.y]+=a;l=Math.max(l,h[b.x][b.y])}});return l},H6=function(a,b){var c=[],d=[],e=1E3/(a.length-1);_.v(a,function(a,b){c.push(b*e);d.push(_.bJ(a))});a=Array(1001);for(var f=0,g=0;1001>g;++g)g>c[f+1]&&++f,
a[g]=f<c.length-1?G6(e*f,g,e*(f+1),d[f],d[f+1]):d[d.length-1],a[g].alpha*=b,a[g].alpha=_.Sa(Math.floor(255*a[g].alpha),0,255);return a},G6=function(a,b,c,d,e){if(a==c)return d;a=(b-a)/(c-a);return new _.ZI(Math.floor((e.j-d.j)*a+d.j),Math.floor((e.f-d.f)*a+d.f),Math.floor((e.b-d.b)*a+d.b),(e.alpha-d.alpha)*a+d.alpha)},J6=function(a){this.f=a.createElement("div");this.b=new I6(this)},I6=_.ha("b"),K6=function(a,b){this.l=a;this.b=1;this.f=[];this.j=b},L6=function(a,b,c){_.Cl(b.R,"");var d=b.b,e,f,g,
h;if(_.tz())e=g=d.createElement("canvas"),_.xk(e),f=e.getContext("2d"),h=1<a.b;else if(1==_.R.type&&_.Mi(_.R.version,8))e=new J6(d),f=e.b,g=e.getDiv(),h=!1;else return;e.width=e.height=256;b.R.appendChild(g);e=a.get("projection");g=a.get("radius");g=Math.round(g/a.b)*a.b;var l=1<<b.zoom,n=b.Mb,q=(256+2*g)/a.b;b=E6(q);for(var r in n)for(var u=n[r],x=e.fromLatLngToPoint(new _.P(u.I,u.J,!0)),B=e.fromLatLngToPoint(new _.P(u.L,u.M,!0)),x=new _.N(Math.min(x.x,B.x),Math.min(x.y,B.y)),x=new _.N(x.x+g/l,x.y+
g/l),u=a.l.search(u),B=0,D=u.length;B<D;++B){var C=u[B],E=e.fromLatLngToPoint(new _.P(C.aa.x,C.aa.y)),M=Math.floor((Math.floor((E.y-x.y)*l)+g)/a.b),E=Math.floor((Math.floor((E.x-x.x)*l)+g)/a.b);0<=M&&M<q&&0<=E&&E<q&&(b[M][E]+=C.weight)}r=a.f;e=Math.floor(r.length/2);g=b.length;l=g-e;n=E6(g);for(q=0;q<g;++q)for(x=b[q],D=n[q],u=0;u<g;++u)if(B=x[u])for(C=u-e,M=Math.min(l,u+e+1),E=Math.max(e,C);E<M;++E)D[E]+=B*r[E-C];b=E6(g-2*e);for(q=0;q<g;++q)for(x=n[q],D=Math.max(e,q-e),C=Math.min(l,q+e+1),M=q-e,u=
e,E=0;u<l;++u,++E)if(B=x[u])for(var I=D;I<C;++I)b[I-e][E]+=B*r[I-M];r=Math.ceil(256/a.b);r=f.createImageData(r,r);e=a.get("gradient");g=a.j;l=e[e.length-1];c=e.length/c;n=r.data;x=q=0;for(u=b.length;x<u;++x)for(B=b[x],D=0,C=B.length;D<C;++D)(M=B[D])||e[0].alpha?(M=e[Math.floor(M*c)]||l,E=g?M.alpha/255:1,n[q++]=M.j*E,n[q++]=M.f*E,n[q++]=M.b*E,n[q++]=M.alpha):q+=4;h?(d=d.createElement("canvas"),d.width=d.height=256/a.b,d.getContext("2d").putImageData(r,0,0),f.scale(a.b,a.b),f.drawImage(d,0,0)):f.putImageData(r,
0,0)},M6=function(a,b,c){this.b=a;a.b=(0,_.p)(this.j,this);this.m=b;this.f=c},N6=function(a,b){_.uf.call(this);this.tileSize=new _.O(256,256);this.j={};var c=_.pf(-100,-300,100,300);this.m=new _.OF(c,void 0);c=_.pf(-90,-180,90,180);this.f=_.eJ(c,function(a,b){return a.aa.b(b.aa)&&a.weight==b.weight});this.P=[];this.C=new _.od;this.b=0;this.l=new K6(this.f,a);this.l.bindTo("projection",this,"projection",!0);this.l.bindTo("gradient",this,"gradient",!0);this.l.bindTo("radius",this,"radius",!0);var d=
this;b(this.C,function(a){L6(d.l,a,d.b)})},O6=function(a,b){var c=b.W,d=1<<b.zoom,e=a.get("radius"),f=new _.N(256*c.x/d,256*c.y/d),c=_.pf((256*c.x-e)/d,(256*c.y-e)/d,(256*(c.x+1)+e)/d,(256*(c.y+1)+e)/d),d=a.get("projection");_.fJ(c,d,f,function(c){c.Hl=b;b.Mb[_.Oa(c)]=c;_.PF(a.m,c)})},P6=function(a,b){_.Pa(b.Mb,function(b,d){a.m.remove(d)});b.Mb={}},Q6=function(a){var b=a.get("maxIntensity");return 1<=b?b:F6(a.get("data"))},R6=function(a,b){b=_.RF(a.m,b);a.get("projection");for(var c=0,d=b.length;c<
d;++c)_.pd(a.C,b[c].Hl)},S6=function(a){_.Pa(a.j,function(b,c){_.pd(a.C,c)})},T6=function(a){var b=a.location||a;a=a.weight||1;return{aa:new _.N(b.lat(),b.lng()),weight:a}},U6=_.ga(),C6;var V6="rgba(102, 255, 0, 0);rgba(102, 255, 0, 1);rgba(147, 255, 0, 1);rgba(193, 255, 0, 1);rgba(238, 255, 0, 1);rgba(244, 227, 0, 1);rgba(249, 198, 0, 1);rgba(255, 170, 0, 1);rgba(255, 113, 0, 1);rgba(255, 57, 0, 1);rgba(255, 0, 0, 1)".split(";");var W6,X6=[137,80,78,71,13,10,26,10,0,0,0,13],Y6=[0,0,0,0,73,69,78,68,174,66,96,130];J6.prototype.getDiv=_.ia("f");I6.prototype.createImageData=function(a,b){for(var c=Array(a*b*4),d=0;d<a*b*4;++d)c[d]=0;return{data:c,width:a,height:b}};
I6.prototype.putImageData=function(a){var b=this.b,c=_.X("img",b.getDiv()),d=a.width,e=a.height,f=a.data,g=11+(4*d+1)*e;a=Array(g+24);a[0]=g>>>24;a[1]=(g&16711680)>>16;a[2]=(g&65280)>>8;a[3]=g&255;a[4]=73;a[5]=68;a[6]=65;a[7]=84;a[8]=8;a[9]=29;a[10]=1;g-=11;a[11]=g&255;a[12]=(g&65280)>>8;a[13]=255-a[11];a[14]=255-a[12];for(var h=1,l=0,n=15,q=0,r=0;r<e;++r){a[n++]=0;for(var l=l+h,u=0;u<4*d;++u)a[n++]=f[q],l+=h+=f[q++]}h%=65521;l%=65521;a[n++]=(l&65280)>>8;a[n++]=l&255;a[n++]=(h&65280)>>8;a[n++]=h&
255;f=D6(a,4,g+15);a[n++]=f>>>24;a[n++]=(f&16711680)>>16;a[n++]=(f&65280)>>8;a[n++]=f&255;f=0;for(g=Y6.length;f<g;++f)a[n++]=Y6[f];if(-1!=d||-1!=e)d=[73,72,68,82,d>>>24,(d&16711680)>>16,(d&65280)>>8,d&255,e>>>24,(e&16711680)>>16,(e&65280)>>8,e&255,8,6,0,0,0],e=D6(d,0,d.length),W6="data:image/png;base64,"+_.Jk(X6.concat(d,[e>>>24,(e&16711680)>>16,(e&65280)>>8,e&255]));a=W6+_.Jk(a);c.src=a;c.width=b.width;c.height=b.height};_.t(K6,_.A);K6.prototype.radius_changed=function(){var a=this.get("radius");_.tz()?this.b=20>a?1:2:this.b=4;for(var a=Math.round(a/this.b),b=a/3,c=[],d=-a;d<=a;d++)c.push(Math.exp(-d*d/(2*b*b)));this.f=c};M6.prototype.j=function(){_.bz(this.f,(0,_.p)(this.l,this))};M6.prototype.l=function(){var a;a:{a=this.b.f;for(var b in a){a=a[b];this.b.remove(a);break a}a=null}a&&this.m(a)};_.t(N6,_.uf);_.k=N6.prototype;_.k.projection=null;_.k.getTile=function(a,b,c){var d=c.createElement("div");_.qf(d,this.tileSize);var e=this.get("opacity");_.m(e)&&_.Xk(d,e);a={R:d,zoom:b,W:a,Mb:{},b:c};d.qa=a;this.j[_.Oa(a)]=a;O6(this,a);this.b||(this.b=Q6(this));L6(this.l,a,this.b);return d};
_.k.data_changed=function(){this.f.clear();var a=this.get("data"),b=this;a&&(a.forEach(function(a){a&&_.dJ(b.f,T6(a))}),this.K());S6(this);_.v(this.P,_.z.removeListener);this.P=[];a&&(this.P=[_.z.bind(a,"insert_at",this,this.Kh),_.z.bind(a,"remove_at",this,this.Lh),_.z.bind(a,"set_at",this,this.ln)])};_.k.Kh=function(a){if(a=this.get("data").getAt(a))a=T6(a),_.dJ(this.f,a),this.K(),R6(this,a.aa)};_.k.Lh=function(a,b){b&&(a=T6(b),this.f.remove(a),this.K(),R6(this,a.aa))};
_.k.ln=function(a,b){this.Lh(0,b);this.Kh(a)};_.k.X=function(){var a=this.b;this.b=Q6(this);_.Ua(a,this.b)||S6(this)};_.k.maxIntensity_changed=function(){this.b=Q6(this);S6(this)};_.k.gradient_changed=function(){S6(this)};_.k.opacity_changed=function(){var a=this.get("opacity");_.Pa(this.j,function(b,c){_.Xk(c.R,a)})};_.k.radius_changed=function(){var a=this;_.Pa(this.j,function(b,c){P6(a,c);O6(a,c)});S6(this)};
_.k.releaseTile=function(a){if(a){var b=a.qa;a.qa=null;delete this.j[_.Oa(b)];var c=this.m;_.Pa(b.Mb,function(a,b){c.remove(b)});_.Cl(b.R,"")}};U6.prototype.b=function(a){var b=a.j,c=a.j=a.get("map");b&&(a.b&&a.b.unbindAll(),a.f&&a.f.release(),_.Gm("Lh","-p",a));if(c){a.b=new _.Fu({dissipating:!0,gradient:V6,opacity:.6,radius:10});a.b.bindTo("dissipating",a);a.b.bindTo("gradient",a);a.b.bindTo("opacity",a);a.b.bindTo("radius",a);b=new _.ht(["stringGradient","opacity"],"colorGradient",function(a,b){return H6(a,b)});b.bindTo("stringGradient",a.b,"gradient",!0);var d=new _.ht(["radius","dissipating","zoom"],"renderingRadius",function(a,b,c){return b?
a:Math.min(Math.round(a*Math.pow(2,c)),256)});d.bindTo("radius",a.b);d.bindTo("zoom",c);d.bindTo("dissipating",a.b);var e=new N6(_.si.Ul(),function(a,b){new M6(a,b,new _.ez(_.dz(250),0))});e.bindTo("projection",c);e.bindTo("data",a);e.bindTo("maxIntensity",a);e.bindTo("gradient",b,"colorGradient");e.bindTo("radius",d,"renderingRadius");_.tz()?(e.bindTo("opacity",a.b),b.set("opacity",1)):b.bindTo("opacity",a.b);_.xF(c,new _.hu(e),"overlayLayer",15,function(b){a.f=b});_.Dm(c,"Lh");_.Fm("Lh","-p",a,
!!c.b)}};_.rc("visualization_impl",new U6);});
