name: google earth enterprise
githuburl: https://github.com/google/earthenterprise/
githubWikiUrl: https://github.com/google/earthenterprise/wiki/
#markdown: redcarpet
#highlighter: pygments
excerpt_separator: <!--more-->

gems:
  - jekyll-paginate

paginate: 1
paginate_path: "blog/page:num"
