name: google earth enterprise
githuburl: https://github.com/google/earthenterprise/
githubWikiUrl: https://github.com/google/earthenterprise/wiki/
releasesUrl: https://github.com/google/earthenterprise/releases

#markdown: redcarpet

#highlighter: pygments
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate

paginate: 1
paginate_path: "blog/page:num"

# Google Analytics Tracking ID
google_analytics: UA—108632131-2
