#-*- Python -*-
#
# Copyright 2018 the Open GEE Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os

Import('env')

env = env.Clone()


for test_name in [
    'add-to-asset-cache_resourcetest',
    'add-to-asset-version-cache_resourcetest',
    'load-raster-project-asset-version-from-xml_resourcetest',
    'parse-raster-project-xml_resourcetest'
]:
    env.test(
        test_name,
        ['{0}.cc'.format(test_name)],
        LIBS = [
            'geautoingest', 'gemiscconfig', 'gecommon', 'yaml-cpp', 'QtCore', 'QtGui', 'gexml', 'xerces-c'
        ])
