#-*- Python -*-
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Import('env')

env.idl(['RasterProductStorage.idl'])


geraster = env.sharedLib('geraster', ['khRasterProduct.cpp',
                                      'pyrio.cpp',
                                      '.idl/RasterProductStorage.cpp',
                                      'khOpacityMask.cpp',
                                      'khRasterProductLevel.cpp',
                                      'Extract.cpp',
                                      'CachedRasterInsetReader.cpp',
                                      'AttributionByExtents.cpp'
                                      ],
                         LIBS=['geautoingest', 'gexml', 'gemiscconfig'])

env.Depends('khRasterProduct.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('pyrio.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('.idl/RasterProductStorage.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('khOpacityMask.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('khRasterProductLevel.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('Extract.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('CachedRasterInsetReader.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])
env.Depends('AttributionByExtents.os', ['../autoingest/.idl/Systemrc.h', '../autoingest/.idl/MiscConfigStorage.h', '.idl/RasterProductStorage.h'])


khrasterffio = env.sharedLib('khrasterffio', ['ffioRasterWriter.cpp',
                                              'ffioRasterReader.cpp',
                                              ],
                             LIBS=['geraster', 'khffio'])

gerastergdal = env.sharedLib('gerastergdal', ['LevelRasterBand.cpp'],
                             LIBS=['geraster', 'gegdal'])

env.install('common_lib', [geraster])
env.install('fusion_lib', [khrasterffio, gerastergdal])
